/*
 * WebConsole NFConfig API
 *
 * API for managing access, mobility, policy, session and PLMN information.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PccFlow struct {

	Description string `json:"description"`

	Direction string `json:"direction"`

	Status string `json:"status,omitempty"`
}
