/*
 * WebConsole NFConfig API
 *
 * API for managing access, mobility, policy, session and PLMN information.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Status string

// List of Status
const (
	ENABLED_UPLINK Status = "ENABLED-UPLINK"
	ENABLED_DOWNLINK Status = "ENABLED-DOWNLINK"
	ENABLED Status = "ENABLED"
	DISABLED Status = "DISABLED"
	REMOVED Status = "REMOVED"
)
