/*
 * WebConsole NFConfig API
 *
 * API for managing access, mobility, policy, session and PLMN information.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PreemptCap string

// List of PreemptCap
const (
	NOT_PREEMPT PreemptCap = "NOT_PREEMPT"
	MAY_PREEMPT PreemptCap = "MAY_PREEMPT"
)
