/*
 * WebConsole NFConfig API
 *
 * API for managing access, mobility, policy, session and PLMN information.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SessionManagement struct {

	SliceName string `json:"sliceName"`

	PlmnId PlmnId `json:"plmnId"`

	Snssai Snssai `json:"snssai"`

	IpDomain []IpDomain `json:"ipDomain,omitempty"`

	Upf Upf `json:"upf,omitempty"`

	GnbNames []string `json:"gnbNames,omitempty"`
}
