/*
 * WebConsole NFConfig API
 *
 * API for managing access, mobility, policy, session and PLMN information.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Direction string

// List of Direction
const (
	DOWNLINK Direction = "DOWNLINK"
	UPLINK Direction = "UPLINK"
	BIDIRECTIONAL Direction = "BIDIRECTIONAL"
	UNSPECIFIED Direction = "UNSPECIFIED"
)
