/*
 * WebConsole NFConfig API
 *
 * API for managing access, mobility, policy, session and PLMN information.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PreemptVuln string

// List of PreemptVuln
const (
	NOT_PREEMPTABLE PreemptVuln = "NOT_PREEMPTABLE"
	PREEMPTABLE PreemptVuln = "PREEMPTABLE"
)
