/*
 * WebConsole NFConfig API
 *
 * API for managing access, mobility, policy, session and PLMN information.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type IpDomain struct {

	DnnName string `json:"dnnName"`

	DnsIpv4 string `json:"dnsIpv4"`

	UeSubnet string `json:"ueSubnet"`

	Mtu int32 `json:"mtu"`
}
