/*
 * Config API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

type DefaultAPI struct {
}

// Get /config/access-and-mobility
// Get Access and Mobility Configuration
func (api *DefaultAPI) ConfigAccessAndMobilityGet(c *gin.Context) {
	resp := AccessAndMobilityConfigResponse{
		Configs: []AccessAndMobilityConfig{
			{
				PlmnId: PlmnId{Mcc: "210", Mnc: "111"},
				Snssai: Snssai{Sst: "1", Sd: "11111"},
				Tacs:   []int32{1, 44, 5},
			},
		},
	}
	c.JSON(http.StatusOK, resp)
}
