/*
 * Config API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PlmnId struct {

	Mcc string `json:"mcc,omitempty"`

	Mnc string `json:"mnc,omitempty"`
}
