/*
 * Config API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AccessAndMobilityConfig struct {

	PlmnId PlmnId `json:"plmnId,omitempty"`

	Snssai Snssai `json:"snssai,omitempty"`

	Tacs []int32 `json:"tacs,omitempty"`
}
