/*
 * Config API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"

	// WARNING!
	// Pass --git-repo-id and --git-user-id properties when generating the code
	//
	openapi "webconsole-proto/rest/api"

	"github.com/gin-gonic/gin"
)

func GetAccessAndMobilityConfig(c *gin.Context) {

}

func main() {
	routes := openapi.ApiHandleFunctions{}

	log.Printf("Server started")

	router := openapi.NewRouter(routes)

	log.Fatal(router.Run(":8080"))
}
